// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pengbin9472/ggbond/ent/predicate"
	"github.com/pengbin9472/ggbond/ent/referralreward"
)

// ReferralRewardUpdate is the builder for updating ReferralReward entities.
type ReferralRewardUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdate) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralRewardUpdate) SetInviterID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableInviterID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralRewardUpdate) AddInviterID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralRewardUpdate) SetInviteeID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableInviteeID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralRewardUpdate) AddInviteeID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdate) SetTriggerRedeemCodeID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetTriggerRedeemCodeID()
	_u.mutation.SetTriggerRedeemCodeID(v)
	return _u
}

// SetNillableTriggerRedeemCodeID sets the "trigger_redeem_code_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableTriggerRedeemCodeID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetTriggerRedeemCodeID(*v)
	}
	return _u
}

// AddTriggerRedeemCodeID adds value to the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdate) AddTriggerRedeemCodeID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddTriggerRedeemCodeID(v)
	return _u
}

// ClearTriggerRedeemCodeID clears the value of the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdate) ClearTriggerRedeemCodeID() *ReferralRewardUpdate {
	_u.mutation.ClearTriggerRedeemCodeID()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdate) SetRewardAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardAmount(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdate) AddRewardAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ReferralRewardUpdate) SetRewardType(v string) *ReferralRewardUpdate {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardType(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardRate sets the "reward_rate" field.
func (_u *ReferralRewardUpdate) SetRewardRate(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetRewardRate()
	_u.mutation.SetRewardRate(v)
	return _u
}

// SetNillableRewardRate sets the "reward_rate" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardRate(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardRate(*v)
	}
	return _u
}

// AddRewardRate adds value to the "reward_rate" field.
func (_u *ReferralRewardUpdate) AddRewardRate(v float64) *ReferralRewardUpdate {
	_u.mutation.AddRewardRate(v)
	return _u
}

// ClearRewardRate clears the value of the "reward_rate" field.
func (_u *ReferralRewardUpdate) ClearRewardRate() *ReferralRewardUpdate {
	_u.mutation.ClearRewardRate()
	return _u
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (_u *ReferralRewardUpdate) SetTriggerCodeValue(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetTriggerCodeValue()
	_u.mutation.SetTriggerCodeValue(v)
	return _u
}

// SetNillableTriggerCodeValue sets the "trigger_code_value" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableTriggerCodeValue(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetTriggerCodeValue(*v)
	}
	return _u
}

// AddTriggerCodeValue adds value to the "trigger_code_value" field.
func (_u *ReferralRewardUpdate) AddTriggerCodeValue(v float64) *ReferralRewardUpdate {
	_u.mutation.AddTriggerCodeValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralRewardUpdate) SetStatus(v string) *ReferralRewardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableStatus(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ReferralRewardUpdate) SetNotes(v string) *ReferralRewardUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableNotes(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ReferralRewardUpdate) ClearNotes() *ReferralRewardUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdate) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralRewardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralRewardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdate) check() error {
	if v, ok := _u.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralRewardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TriggerRedeemCodeID(); ok {
		_spec.SetField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggerRedeemCodeID(); ok {
		_spec.AddField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.TriggerRedeemCodeIDCleared() {
		_spec.ClearField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardRate(); ok {
		_spec.SetField(referralreward.FieldRewardRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardRate(); ok {
		_spec.AddField(referralreward.FieldRewardRate, field.TypeFloat64, value)
	}
	if _u.mutation.RewardRateCleared() {
		_spec.ClearField(referralreward.FieldRewardRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TriggerCodeValue(); ok {
		_spec.SetField(referralreward.FieldTriggerCodeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTriggerCodeValue(); ok {
		_spec.AddField(referralreward.FieldTriggerCodeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(referralreward.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(referralreward.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralRewardUpdateOne is the builder for updating a single ReferralReward entity.
type ReferralRewardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralRewardUpdateOne) SetInviterID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableInviterID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralRewardUpdateOne) AddInviterID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralRewardUpdateOne) SetInviteeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableInviteeID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralRewardUpdateOne) AddInviteeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdateOne) SetTriggerRedeemCodeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetTriggerRedeemCodeID()
	_u.mutation.SetTriggerRedeemCodeID(v)
	return _u
}

// SetNillableTriggerRedeemCodeID sets the "trigger_redeem_code_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableTriggerRedeemCodeID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetTriggerRedeemCodeID(*v)
	}
	return _u
}

// AddTriggerRedeemCodeID adds value to the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdateOne) AddTriggerRedeemCodeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddTriggerRedeemCodeID(v)
	return _u
}

// ClearTriggerRedeemCodeID clears the value of the "trigger_redeem_code_id" field.
func (_u *ReferralRewardUpdateOne) ClearTriggerRedeemCodeID() *ReferralRewardUpdateOne {
	_u.mutation.ClearTriggerRedeemCodeID()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) SetRewardAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardAmount(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) AddRewardAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ReferralRewardUpdateOne) SetRewardType(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardType(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetRewardRate sets the "reward_rate" field.
func (_u *ReferralRewardUpdateOne) SetRewardRate(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetRewardRate()
	_u.mutation.SetRewardRate(v)
	return _u
}

// SetNillableRewardRate sets the "reward_rate" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardRate(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardRate(*v)
	}
	return _u
}

// AddRewardRate adds value to the "reward_rate" field.
func (_u *ReferralRewardUpdateOne) AddRewardRate(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddRewardRate(v)
	return _u
}

// ClearRewardRate clears the value of the "reward_rate" field.
func (_u *ReferralRewardUpdateOne) ClearRewardRate() *ReferralRewardUpdateOne {
	_u.mutation.ClearRewardRate()
	return _u
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (_u *ReferralRewardUpdateOne) SetTriggerCodeValue(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetTriggerCodeValue()
	_u.mutation.SetTriggerCodeValue(v)
	return _u
}

// SetNillableTriggerCodeValue sets the "trigger_code_value" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableTriggerCodeValue(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetTriggerCodeValue(*v)
	}
	return _u
}

// AddTriggerCodeValue adds value to the "trigger_code_value" field.
func (_u *ReferralRewardUpdateOne) AddTriggerCodeValue(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddTriggerCodeValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralRewardUpdateOne) SetStatus(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableStatus(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ReferralRewardUpdateOne) SetNotes(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableNotes(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ReferralRewardUpdateOne) ClearNotes() *ReferralRewardUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdateOne) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdateOne) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralRewardUpdateOne) Select(field string, fields ...string) *ReferralRewardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralReward entity.
func (_u *ReferralRewardUpdateOne) Save(ctx context.Context) (*ReferralReward, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) SaveX(ctx context.Context) *ReferralReward {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralRewardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdateOne) check() error {
	if v, ok := _u.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralRewardUpdateOne) sqlSave(ctx context.Context) (_node *ReferralReward, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralReward.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralreward.FieldID)
		for _, f := range fields {
			if !referralreward.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralreward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TriggerRedeemCodeID(); ok {
		_spec.SetField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggerRedeemCodeID(); ok {
		_spec.AddField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.TriggerRedeemCodeIDCleared() {
		_spec.ClearField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RewardRate(); ok {
		_spec.SetField(referralreward.FieldRewardRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardRate(); ok {
		_spec.AddField(referralreward.FieldRewardRate, field.TypeFloat64, value)
	}
	if _u.mutation.RewardRateCleared() {
		_spec.ClearField(referralreward.FieldRewardRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TriggerCodeValue(); ok {
		_spec.SetField(referralreward.FieldTriggerCodeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTriggerCodeValue(); ok {
		_spec.AddField(referralreward.FieldTriggerCodeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(referralreward.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(referralreward.FieldNotes, field.TypeString)
	}
	_node = &ReferralReward{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
