// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pengbin9472/ggbond/ent/referralreward"
)

// ReferralRewardCreate is the builder for creating a ReferralReward entity.
type ReferralRewardCreate struct {
	config
	mutation *ReferralRewardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *ReferralRewardCreate) SetInviterID(v int64) *ReferralRewardCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *ReferralRewardCreate) SetInviteeID(v int64) *ReferralRewardCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (_c *ReferralRewardCreate) SetTriggerRedeemCodeID(v int64) *ReferralRewardCreate {
	_c.mutation.SetTriggerRedeemCodeID(v)
	return _c
}

// SetNillableTriggerRedeemCodeID sets the "trigger_redeem_code_id" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableTriggerRedeemCodeID(v *int64) *ReferralRewardCreate {
	if v != nil {
		_c.SetTriggerRedeemCodeID(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *ReferralRewardCreate) SetRewardAmount(v float64) *ReferralRewardCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *ReferralRewardCreate) SetRewardType(v string) *ReferralRewardCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableRewardType(v *string) *ReferralRewardCreate {
	if v != nil {
		_c.SetRewardType(*v)
	}
	return _c
}

// SetRewardRate sets the "reward_rate" field.
func (_c *ReferralRewardCreate) SetRewardRate(v float64) *ReferralRewardCreate {
	_c.mutation.SetRewardRate(v)
	return _c
}

// SetNillableRewardRate sets the "reward_rate" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableRewardRate(v *float64) *ReferralRewardCreate {
	if v != nil {
		_c.SetRewardRate(*v)
	}
	return _c
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (_c *ReferralRewardCreate) SetTriggerCodeValue(v float64) *ReferralRewardCreate {
	_c.mutation.SetTriggerCodeValue(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReferralRewardCreate) SetStatus(v string) *ReferralRewardCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableStatus(v *string) *ReferralRewardCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ReferralRewardCreate) SetNotes(v string) *ReferralRewardCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableNotes(v *string) *ReferralRewardCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralRewardCreate) SetCreatedAt(v time.Time) *ReferralRewardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableCreatedAt(v *time.Time) *ReferralRewardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_c *ReferralRewardCreate) Mutation() *ReferralRewardMutation {
	return _c.mutation
}

// Save creates the ReferralReward in the database.
func (_c *ReferralRewardCreate) Save(ctx context.Context) (*ReferralReward, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralRewardCreate) SaveX(ctx context.Context) *ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralRewardCreate) defaults() {
	if _, ok := _c.mutation.RewardType(); !ok {
		v := referralreward.DefaultRewardType
		_c.mutation.SetRewardType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := referralreward.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralreward.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralRewardCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "ReferralReward.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "ReferralReward.invitee_id"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "ReferralReward.reward_amount"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "ReferralReward.reward_type"`)}
	}
	if v, ok := _c.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerCodeValue(); !ok {
		return &ValidationError{Name: "trigger_code_value", err: errors.New(`ent: missing required field "ReferralReward.trigger_code_value"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralReward.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralReward.created_at"`)}
	}
	return nil
}

func (_c *ReferralRewardCreate) sqlSave(ctx context.Context) (*ReferralReward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralRewardCreate) createSpec() (*ReferralReward, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralReward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralreward.Table, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
		_node.InviterID = value
	}
	if value, ok := _c.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
		_node.InviteeID = value
	}
	if value, ok := _c.mutation.TriggerRedeemCodeID(); ok {
		_spec.SetField(referralreward.FieldTriggerRedeemCodeID, field.TypeInt64, value)
		_node.TriggerRedeemCodeID = &value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.RewardRate(); ok {
		_spec.SetField(referralreward.FieldRewardRate, field.TypeFloat64, value)
		_node.RewardRate = &value
	}
	if value, ok := _c.mutation.TriggerCodeValue(); ok {
		_spec.SetField(referralreward.FieldTriggerCodeValue, field.TypeFloat64, value)
		_node.TriggerCodeValue = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(referralreward.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralreward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertOne {
	_c.conflict = opts
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflictColumns(columns ...string) *ReferralRewardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

type (
	// ReferralRewardUpsertOne is the builder for "upsert"-ing
	//  one ReferralReward node.
	ReferralRewardUpsertOne struct {
		create *ReferralRewardCreate
	}

	// ReferralRewardUpsert is the "OnConflict" setter.
	ReferralRewardUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsert) SetInviterID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateInviterID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldInviterID)
	return u
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsert) AddInviterID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldInviterID, v)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsert) SetInviteeID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateInviteeID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldInviteeID)
	return u
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsert) AddInviteeID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldInviteeID, v)
	return u
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsert) SetTriggerRedeemCodeID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldTriggerRedeemCodeID, v)
	return u
}

// UpdateTriggerRedeemCodeID sets the "trigger_redeem_code_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateTriggerRedeemCodeID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldTriggerRedeemCodeID)
	return u
}

// AddTriggerRedeemCodeID adds v to the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsert) AddTriggerRedeemCodeID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldTriggerRedeemCodeID, v)
	return u
}

// ClearTriggerRedeemCodeID clears the value of the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsert) ClearTriggerRedeemCodeID() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldTriggerRedeemCodeID)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsert) SetRewardAmount(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardAmount() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsert) AddRewardAmount(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldRewardAmount, v)
	return u
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsert) SetRewardType(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardType, v)
	return u
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardType() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardType)
	return u
}

// SetRewardRate sets the "reward_rate" field.
func (u *ReferralRewardUpsert) SetRewardRate(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardRate, v)
	return u
}

// UpdateRewardRate sets the "reward_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardRate() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardRate)
	return u
}

// AddRewardRate adds v to the "reward_rate" field.
func (u *ReferralRewardUpsert) AddRewardRate(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldRewardRate, v)
	return u
}

// ClearRewardRate clears the value of the "reward_rate" field.
func (u *ReferralRewardUpsert) ClearRewardRate() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldRewardRate)
	return u
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (u *ReferralRewardUpsert) SetTriggerCodeValue(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldTriggerCodeValue, v)
	return u
}

// UpdateTriggerCodeValue sets the "trigger_code_value" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateTriggerCodeValue() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldTriggerCodeValue)
	return u
}

// AddTriggerCodeValue adds v to the "trigger_code_value" field.
func (u *ReferralRewardUpsert) AddTriggerCodeValue(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldTriggerCodeValue, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsert) SetStatus(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateStatus() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *ReferralRewardUpsert) SetNotes(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateNotes() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralRewardUpsert) ClearNotes() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertOne) UpdateNewValues() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralreward.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralRewardUpsertOne) Ignore() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertOne) DoNothing() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreate.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertOne) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsertOne) SetInviterID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsertOne) AddInviterID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateInviterID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsertOne) SetInviteeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsertOne) AddInviteeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateInviteeID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviteeID()
	})
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertOne) SetTriggerRedeemCodeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetTriggerRedeemCodeID(v)
	})
}

// AddTriggerRedeemCodeID adds v to the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertOne) AddTriggerRedeemCodeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddTriggerRedeemCodeID(v)
	})
}

// UpdateTriggerRedeemCodeID sets the "trigger_redeem_code_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateTriggerRedeemCodeID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateTriggerRedeemCodeID()
	})
}

// ClearTriggerRedeemCodeID clears the value of the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertOne) ClearTriggerRedeemCodeID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearTriggerRedeemCodeID()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertOne) SetRewardAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertOne) AddRewardAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardAmount() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsertOne) SetRewardType(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardType() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardRate sets the "reward_rate" field.
func (u *ReferralRewardUpsertOne) SetRewardRate(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardRate(v)
	})
}

// AddRewardRate adds v to the "reward_rate" field.
func (u *ReferralRewardUpsertOne) AddRewardRate(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardRate(v)
	})
}

// UpdateRewardRate sets the "reward_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardRate() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardRate()
	})
}

// ClearRewardRate clears the value of the "reward_rate" field.
func (u *ReferralRewardUpsertOne) ClearRewardRate() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearRewardRate()
	})
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (u *ReferralRewardUpsertOne) SetTriggerCodeValue(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetTriggerCodeValue(v)
	})
}

// AddTriggerCodeValue adds v to the "trigger_code_value" field.
func (u *ReferralRewardUpsertOne) AddTriggerCodeValue(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddTriggerCodeValue(v)
	})
}

// UpdateTriggerCodeValue sets the "trigger_code_value" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateTriggerCodeValue() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateTriggerCodeValue()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsertOne) SetStatus(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateStatus() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralRewardUpsertOne) SetNotes(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateNotes() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralRewardUpsertOne) ClearNotes() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralRewardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralRewardCreateBulk is the builder for creating many ReferralReward entities in bulk.
type ReferralRewardCreateBulk struct {
	config
	err      error
	builders []*ReferralRewardCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralReward entities in the database.
func (_c *ReferralRewardCreateBulk) Save(ctx context.Context) ([]*ReferralReward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralReward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralRewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) SaveX(ctx context.Context) []*ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertBulk {
	_c.conflict = opts
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflictColumns(columns ...string) *ReferralRewardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// ReferralRewardUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralReward nodes.
type ReferralRewardUpsertBulk struct {
	create *ReferralRewardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) UpdateNewValues() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralreward.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) Ignore() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertBulk) DoNothing() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertBulk) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsertBulk) SetInviterID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsertBulk) AddInviterID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateInviterID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsertBulk) SetInviteeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsertBulk) AddInviteeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateInviteeID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviteeID()
	})
}

// SetTriggerRedeemCodeID sets the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertBulk) SetTriggerRedeemCodeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetTriggerRedeemCodeID(v)
	})
}

// AddTriggerRedeemCodeID adds v to the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertBulk) AddTriggerRedeemCodeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddTriggerRedeemCodeID(v)
	})
}

// UpdateTriggerRedeemCodeID sets the "trigger_redeem_code_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateTriggerRedeemCodeID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateTriggerRedeemCodeID()
	})
}

// ClearTriggerRedeemCodeID clears the value of the "trigger_redeem_code_id" field.
func (u *ReferralRewardUpsertBulk) ClearTriggerRedeemCodeID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearTriggerRedeemCodeID()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) SetRewardAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) AddRewardAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardAmount() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsertBulk) SetRewardType(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardType() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardRate sets the "reward_rate" field.
func (u *ReferralRewardUpsertBulk) SetRewardRate(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardRate(v)
	})
}

// AddRewardRate adds v to the "reward_rate" field.
func (u *ReferralRewardUpsertBulk) AddRewardRate(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardRate(v)
	})
}

// UpdateRewardRate sets the "reward_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardRate() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardRate()
	})
}

// ClearRewardRate clears the value of the "reward_rate" field.
func (u *ReferralRewardUpsertBulk) ClearRewardRate() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearRewardRate()
	})
}

// SetTriggerCodeValue sets the "trigger_code_value" field.
func (u *ReferralRewardUpsertBulk) SetTriggerCodeValue(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetTriggerCodeValue(v)
	})
}

// AddTriggerCodeValue adds v to the "trigger_code_value" field.
func (u *ReferralRewardUpsertBulk) AddTriggerCodeValue(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddTriggerCodeValue(v)
	})
}

// UpdateTriggerCodeValue sets the "trigger_code_value" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateTriggerCodeValue() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateTriggerCodeValue()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsertBulk) SetStatus(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateStatus() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ReferralRewardUpsertBulk) SetNotes(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateNotes() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ReferralRewardUpsertBulk) ClearNotes() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralRewardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
