// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pengbin9472/ggbond/ent/referralreward"
)

// ReferralReward is the model entity for the ReferralReward schema.
type ReferralReward struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID int64 `json:"inviter_id,omitempty"`
	// InviteeID holds the value of the "invitee_id" field.
	InviteeID int64 `json:"invitee_id,omitempty"`
	// TriggerRedeemCodeID holds the value of the "trigger_redeem_code_id" field.
	TriggerRedeemCodeID *int64 `json:"trigger_redeem_code_id,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// RewardType holds the value of the "reward_type" field.
	RewardType string `json:"reward_type,omitempty"`
	// RewardRate holds the value of the "reward_rate" field.
	RewardRate *float64 `json:"reward_rate,omitempty"`
	// TriggerCodeValue holds the value of the "trigger_code_value" field.
	TriggerCodeValue float64 `json:"trigger_code_value,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralReward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldRewardAmount, referralreward.FieldRewardRate, referralreward.FieldTriggerCodeValue:
			values[i] = new(sql.NullFloat64)
		case referralreward.FieldID, referralreward.FieldInviterID, referralreward.FieldInviteeID, referralreward.FieldTriggerRedeemCodeID:
			values[i] = new(sql.NullInt64)
		case referralreward.FieldRewardType, referralreward.FieldStatus, referralreward.FieldNotes:
			values[i] = new(sql.NullString)
		case referralreward.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralReward fields.
func (_m *ReferralReward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralreward.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = value.Int64
			}
		case referralreward.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				_m.InviteeID = value.Int64
			}
		case referralreward.FieldTriggerRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_redeem_code_id", values[i])
			} else if value.Valid {
				_m.TriggerRedeemCodeID = new(int64)
				*_m.TriggerRedeemCodeID = value.Int64
			}
		case referralreward.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case referralreward.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = value.String
			}
		case referralreward.FieldRewardRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_rate", values[i])
			} else if value.Valid {
				_m.RewardRate = new(float64)
				*_m.RewardRate = value.Float64
			}
		case referralreward.FieldTriggerCodeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_code_value", values[i])
			} else if value.Valid {
				_m.TriggerCodeValue = value.Float64
			}
		case referralreward.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referralreward.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case referralreward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralReward.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralReward) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralReward.
// Note that you need to call ReferralReward.Unwrap() before calling this method if this ReferralReward
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralReward) Update() *ReferralRewardUpdateOne {
	return NewReferralRewardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralReward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralReward) Unwrap() *ReferralReward {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralReward is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralReward) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralReward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeID))
	builder.WriteString(", ")
	if v := _m.TriggerRedeemCodeID; v != nil {
		builder.WriteString("trigger_redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(_m.RewardType)
	builder.WriteString(", ")
	if v := _m.RewardRate; v != nil {
		builder.WriteString("reward_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("trigger_code_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerCodeValue))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralRewards is a parsable slice of ReferralReward.
type ReferralRewards []*ReferralReward
