// Code generated by ent, DO NOT EDIT.

package referralreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the referralreward type in the database.
	Label = "referral_reward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldInviteeID holds the string denoting the invitee_id field in the database.
	FieldInviteeID = "invitee_id"
	// FieldTriggerRedeemCodeID holds the string denoting the trigger_redeem_code_id field in the database.
	FieldTriggerRedeemCodeID = "trigger_redeem_code_id"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldRewardRate holds the string denoting the reward_rate field in the database.
	FieldRewardRate = "reward_rate"
	// FieldTriggerCodeValue holds the string denoting the trigger_code_value field in the database.
	FieldTriggerCodeValue = "trigger_code_value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the referralreward in the database.
	Table = "referral_rewards"
)

// Columns holds all SQL columns for referralreward fields.
var Columns = []string{
	FieldID,
	FieldInviterID,
	FieldInviteeID,
	FieldTriggerRedeemCodeID,
	FieldRewardAmount,
	FieldRewardType,
	FieldRewardRate,
	FieldTriggerCodeValue,
	FieldStatus,
	FieldNotes,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRewardType holds the default value on creation for the "reward_type" field.
	DefaultRewardType string
	// RewardTypeValidator is a validator for the "reward_type" field. It is called by the builders before save.
	RewardTypeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralReward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByInviteeID orders the results by the invitee_id field.
func ByInviteeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeID, opts...).ToFunc()
}

// ByTriggerRedeemCodeID orders the results by the trigger_redeem_code_id field.
func ByTriggerRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerRedeemCodeID, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// ByRewardRate orders the results by the reward_rate field.
func ByRewardRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardRate, opts...).ToFunc()
}

// ByTriggerCodeValue orders the results by the trigger_code_value field.
func ByTriggerCodeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerCodeValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
