// Code generated by ent, DO NOT EDIT.

package referralreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/pengbin9472/ggbond/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldID, id))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldInviterID, v))
}

// InviteeID applies equality check predicate on the "invitee_id" field. It's identical to InviteeIDEQ.
func InviteeID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldInviteeID, v))
}

// TriggerRedeemCodeID applies equality check predicate on the "trigger_redeem_code_id" field. It's identical to TriggerRedeemCodeIDEQ.
func TriggerRedeemCodeID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldTriggerRedeemCodeID, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardType applies equality check predicate on the "reward_type" field. It's identical to RewardTypeEQ.
func RewardType(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardType, v))
}

// RewardRate applies equality check predicate on the "reward_rate" field. It's identical to RewardRateEQ.
func RewardRate(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardRate, v))
}

// TriggerCodeValue applies equality check predicate on the "trigger_code_value" field. It's identical to TriggerCodeValueEQ.
func TriggerCodeValue(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldTriggerCodeValue, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCreatedAt, v))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviterIDGT applies the GT predicate on the "inviter_id" field.
func InviterIDGT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldInviterID, v))
}

// InviterIDGTE applies the GTE predicate on the "inviter_id" field.
func InviterIDGTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldInviterID, v))
}

// InviterIDLT applies the LT predicate on the "inviter_id" field.
func InviterIDLT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldInviterID, v))
}

// InviterIDLTE applies the LTE predicate on the "inviter_id" field.
func InviterIDLTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldInviterID, v))
}

// InviteeIDEQ applies the EQ predicate on the "invitee_id" field.
func InviteeIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldInviteeID, v))
}

// InviteeIDNEQ applies the NEQ predicate on the "invitee_id" field.
func InviteeIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldInviteeID, v))
}

// InviteeIDIn applies the In predicate on the "invitee_id" field.
func InviteeIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldInviteeID, vs...))
}

// InviteeIDNotIn applies the NotIn predicate on the "invitee_id" field.
func InviteeIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldInviteeID, vs...))
}

// InviteeIDGT applies the GT predicate on the "invitee_id" field.
func InviteeIDGT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldInviteeID, v))
}

// InviteeIDGTE applies the GTE predicate on the "invitee_id" field.
func InviteeIDGTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldInviteeID, v))
}

// InviteeIDLT applies the LT predicate on the "invitee_id" field.
func InviteeIDLT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldInviteeID, v))
}

// InviteeIDLTE applies the LTE predicate on the "invitee_id" field.
func InviteeIDLTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldInviteeID, v))
}

// TriggerRedeemCodeIDEQ applies the EQ predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDNEQ applies the NEQ predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDIn applies the In predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldTriggerRedeemCodeID, vs...))
}

// TriggerRedeemCodeIDNotIn applies the NotIn predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldTriggerRedeemCodeID, vs...))
}

// TriggerRedeemCodeIDGT applies the GT predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDGT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDGTE applies the GTE predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDGTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDLT applies the LT predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDLT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDLTE applies the LTE predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDLTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldTriggerRedeemCodeID, v))
}

// TriggerRedeemCodeIDIsNil applies the IsNil predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldTriggerRedeemCodeID))
}

// TriggerRedeemCodeIDNotNil applies the NotNil predicate on the "trigger_redeem_code_id" field.
func TriggerRedeemCodeIDNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldTriggerRedeemCodeID))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldRewardAmount, v))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardTypeGT applies the GT predicate on the "reward_type" field.
func RewardTypeGT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldRewardType, v))
}

// RewardTypeGTE applies the GTE predicate on the "reward_type" field.
func RewardTypeGTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldRewardType, v))
}

// RewardTypeLT applies the LT predicate on the "reward_type" field.
func RewardTypeLT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldRewardType, v))
}

// RewardTypeLTE applies the LTE predicate on the "reward_type" field.
func RewardTypeLTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldRewardType, v))
}

// RewardTypeContains applies the Contains predicate on the "reward_type" field.
func RewardTypeContains(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContains(FieldRewardType, v))
}

// RewardTypeHasPrefix applies the HasPrefix predicate on the "reward_type" field.
func RewardTypeHasPrefix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasPrefix(FieldRewardType, v))
}

// RewardTypeHasSuffix applies the HasSuffix predicate on the "reward_type" field.
func RewardTypeHasSuffix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasSuffix(FieldRewardType, v))
}

// RewardTypeEqualFold applies the EqualFold predicate on the "reward_type" field.
func RewardTypeEqualFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEqualFold(FieldRewardType, v))
}

// RewardTypeContainsFold applies the ContainsFold predicate on the "reward_type" field.
func RewardTypeContainsFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContainsFold(FieldRewardType, v))
}

// RewardRateEQ applies the EQ predicate on the "reward_rate" field.
func RewardRateEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardRate, v))
}

// RewardRateNEQ applies the NEQ predicate on the "reward_rate" field.
func RewardRateNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRewardRate, v))
}

// RewardRateIn applies the In predicate on the "reward_rate" field.
func RewardRateIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRewardRate, vs...))
}

// RewardRateNotIn applies the NotIn predicate on the "reward_rate" field.
func RewardRateNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRewardRate, vs...))
}

// RewardRateGT applies the GT predicate on the "reward_rate" field.
func RewardRateGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldRewardRate, v))
}

// RewardRateGTE applies the GTE predicate on the "reward_rate" field.
func RewardRateGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldRewardRate, v))
}

// RewardRateLT applies the LT predicate on the "reward_rate" field.
func RewardRateLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldRewardRate, v))
}

// RewardRateLTE applies the LTE predicate on the "reward_rate" field.
func RewardRateLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldRewardRate, v))
}

// RewardRateIsNil applies the IsNil predicate on the "reward_rate" field.
func RewardRateIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldRewardRate))
}

// RewardRateNotNil applies the NotNil predicate on the "reward_rate" field.
func RewardRateNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldRewardRate))
}

// TriggerCodeValueEQ applies the EQ predicate on the "trigger_code_value" field.
func TriggerCodeValueEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldTriggerCodeValue, v))
}

// TriggerCodeValueNEQ applies the NEQ predicate on the "trigger_code_value" field.
func TriggerCodeValueNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldTriggerCodeValue, v))
}

// TriggerCodeValueIn applies the In predicate on the "trigger_code_value" field.
func TriggerCodeValueIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldTriggerCodeValue, vs...))
}

// TriggerCodeValueNotIn applies the NotIn predicate on the "trigger_code_value" field.
func TriggerCodeValueNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldTriggerCodeValue, vs...))
}

// TriggerCodeValueGT applies the GT predicate on the "trigger_code_value" field.
func TriggerCodeValueGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldTriggerCodeValue, v))
}

// TriggerCodeValueGTE applies the GTE predicate on the "trigger_code_value" field.
func TriggerCodeValueGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldTriggerCodeValue, v))
}

// TriggerCodeValueLT applies the LT predicate on the "trigger_code_value" field.
func TriggerCodeValueLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldTriggerCodeValue, v))
}

// TriggerCodeValueLTE applies the LTE predicate on the "trigger_code_value" field.
func TriggerCodeValueLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldTriggerCodeValue, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.NotPredicates(p))
}
